Repository kubescape/kubescape, pull requests merged in 2022-12, with the labels that each got.

#948 Print host scanner version
  core/pkg/hostsensorutils/hostsensor.yaml
  core/pkg/hostsensorutils/hostsensorgetfrompod.go
Labels: feature, logs/add

#956 Enhance `host-scanner`
  .github/workflows/build-image.yaml
  .github/workflows/build.yaml
  .github/workflows/build_dev.yaml
  README.md
  cmd/download/download.go
  cmd/root.go
  cmd/scan/control.go
  cmd/scan/framework.go
  cmd/scan/scan.go
  cmd/scan/scan_test.go
  core/cautils/datastructures.go
  core/cautils/getter/downloadreleasedpolicy.go
  core/cautils/getter/loadpolicy.go
  core/cautils/gitparse_test.go
  core/cautils/localgitrepository.go
  core/cautils/scaninfo.go
  core/cautils/versioncheck.go
  core/cautils/workloadmappingutils.go
  core/core/download.go
  core/core/initutils.go
  core/core/list.go
  core/core/scan.go
  core/pkg/hostsensorutils/hostsensor.yaml
  core/pkg/hostsensorutils/hostsensorgetfrompod.go
  core/pkg/hostsensorutils/utils.go
  core/pkg/opaprocessor/processorhandler.go
  core/pkg/policyhandler/handlenotification.go
  core/pkg/resourcehandler/filesloader.go
  core/pkg/resourcehandler/filesloaderutils.go
  core/pkg/resourcehandler/k8sresources.go
  core/pkg/resourcehandler/k8sresourcesutils.go
  core/pkg/resourcehandler/registrydata.go
  core/pkg/resourcehandler/remotegitutils.go
  core/pkg/resourcehandler/urlloader.go
  core/pkg/resourcesprioritization/prioritizationhandler.go
  core/pkg/resultshandling/printer/v2/html/report.gohtml
  core/pkg/resultshandling/printer/v2/htmlprinter.go
  core/pkg/resultshandling/printer/v2/junit.go
  core/pkg/resultshandling/printer/v2/prettyprinter.go
  core/pkg/resultshandling/printer/v2/reportingstructs.go
  core/pkg/resultshandling/printer/v2/utils.go
  core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
  core/pkg/resultshandling/reporter/v2/reporteventreceiver_test.go
  core/pkg/resultshandling/results.go
  docs/Kubescape flow.drawio
  docs/architecture.drawio.svg
  go.mod
  go.sum
  httphandler/docs/swagger.yaml
  httphandler/go.mod
  httphandler/go.sum
  httphandler/handlerequests/v1/requestshandler.go
Labels: release

#986 Cosmetic changes
  cmd/scan/framework.go
  core/pkg/policyhandler/handlepullpolicies.go
  core/pkg/policyhandler/handlepullpolicies_test.go
  core/pkg/policyhandler/handlepullpoliciesutils.go
  core/pkg/policyhandler/handlepullpoliciesutils_test.go
  core/pkg/resourcehandler/k8sresources.go
  core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
  install.sh
Labels: logs/change
