Repository kubescape/kubescape, pull requests merged in 2022-11, with the labels that each got.

#876 Per 335 removing support for submitting results without accountid
  README.md
  cmd/scan/scan.go
  core/core/initutils.go
  httphandler/README.md
  httphandler/examples/microservice/README.md
Labels: feature

#888 Inform User if something is wrong with "controls-inputs" file they provided
  core/cautils/getter/loadpolicy.go
  core/pkg/policyhandler/handlepullpolicies.go
Labels: logs/add

#825 added adaptor
  core/cautils/getter/gcpcloudapi.go
  core/pkg/registryadaptors/gcp/v1/Readme.md
  core/pkg/registryadaptors/gcp/v1/datastructure.go
  core/pkg/registryadaptors/gcp/v1/gcpadaptor.go
  core/pkg/registryadaptors/gcp/v1/gcpadaptor_test.go
  core/pkg/registryadaptors/gcp/v1/gcpadaptormock.go
  core/pkg/registryadaptors/gcp/v1/gcpadaptorutils.go
  core/pkg/registryadaptors/registryvulnerabilities/datastructures.go
  core/pkg/resourcehandler/registrydata.go
  go.mod
  go.sum
  httphandler/go.mod
  httphandler/go.sum
Labels: feature

#894 Enhancing CLI capabilities and SARIF output
  .github/workflows/build.yaml
  README.md
  cmd/root.go
  cmd/scan/scan.go
  cmd/update/update.go
  core/cautils/fileutils.go
  core/cautils/getter/downloadreleasedpolicy.go
  core/cautils/getter/gcpcloudapi.go
  core/cautils/getter/loadpolicy.go
  core/cautils/rootinfo.go
  core/cautils/scaninfo.go
  core/cautils/versioncheck.go
  core/core/download.go
  core/core/initutils.go
  core/core/list.go
  core/core/scan.go
  core/pkg/policyhandler/handlepullpolicies.go
  core/pkg/registryadaptors/gcp/v1/Readme.md
  core/pkg/registryadaptors/gcp/v1/datastructure.go
  core/pkg/registryadaptors/gcp/v1/gcpadaptor.go
  core/pkg/registryadaptors/gcp/v1/gcpadaptor_test.go
  core/pkg/registryadaptors/gcp/v1/gcpadaptormock.go
  core/pkg/registryadaptors/gcp/v1/gcpadaptorutils.go
  core/pkg/registryadaptors/registryvulnerabilities/datastructures.go
  core/pkg/resourcehandler/fieldselector.go
  core/pkg/resourcehandler/k8sresources.go
  core/pkg/resourcehandler/registrydata.go
  core/pkg/resultshandling/locationresolver/locationresolver.go
  core/pkg/resultshandling/locationresolver/locationresolver_test.go
  core/pkg/resultshandling/printer/printresults.go
  core/pkg/resultshandling/printer/v2/sarifprinter.go
  core/pkg/resultshandling/printer/v2/sarifprinter_test.go
  core/pkg/resultshandling/reporter/v2/mockreporter.go
  core/pkg/resultshandling/reporter/v2/reporteventreceiver_test.go
  core/pkg/resultshandling/results.go
  go.mod
  go.sum
  httphandler/README.md
  httphandler/examples/microservice/README.md
  httphandler/go.mod
  httphandler/go.sum
  install.sh
  main.go
Labels: feature, release

#907 remove deprecated ioutil package
  core/cautils/getter/kscloudapi.go
  core/cautils/helmchart_test.go
  core/cautils/scaninfo.go
  httphandler/handlerequests/v1/requestparser.go
Labels: maintenance

#938 Adding CloudProvider to postureControlInputs
  core/pkg/opaprocessor/processorhandler.go
  core/pkg/policyhandler/handlenotification.go
Labels: feature
