Repository kubescape/kubescape, pull requests merged in 2023-01, with the labels that each got.

#1000 Release
  .github/workflows/01-golang-lint.yaml
  .github/workflows/build.yaml
  .github/workflows/test.yaml
  .gitignore
  .golangci.yml
  README.md
  build/Dockerfile
  cmd/completion/completion.go
  cmd/scan/scan.go
  core/cautils/customerloader.go
  core/cautils/datastructures.go
  core/cautils/getter/getpoliciesutils.go
  core/cautils/getter/loadpolicy.go
  core/cautils/localgitrepository_test.go
  core/cautils/scaninfo.go
  core/core/download.go
  core/core/initutils.go
  core/core/initutils_test.go
  core/core/scan.go
  core/pkg/containerscan/containerscan_mock.go
  core/pkg/opaprocessor/processorhandler.go
  core/pkg/opaprocessor/processorhandlerutils.go
  core/pkg/policyhandler/handlenotification.go
  core/pkg/policyhandler/handlenotification_test.go
  core/pkg/policyhandler/kubeconfig_mock.json
  core/pkg/registryadaptors/armosec/v1/civksadaptor.go
  core/pkg/registryadaptors/gcp/v1/gcpadaptor.go
  core/pkg/registryadaptors/gcp/v1/gcpadaptormock.go
  core/pkg/resourcehandler/k8sresources.go
  core/pkg/resourcehandler/remotegitutils.go
  core/pkg/resourcesprioritization/prioritizationhandler.go
  core/pkg/resourcesprioritization/prioritizationhandler_test.go
  core/pkg/resultshandling/gotree/gotree.go
  core/pkg/resultshandling/printer/v2/attacktracks.go
  core/pkg/resultshandling/printer/v2/prettyprinter.go
  core/pkg/resultshandling/printer/v2/prometheusutils.go
  core/pkg/resultshandling/printer/v2/sarifprinter.go
  core/pkg/resultshandling/reporter/v2/mockreporter.go
  core/pkg/resultshandling/reporter/v2/mockreporter_test.go
  core/pkg/resultshandling/results.go
  go.mod
  go.sum
  httphandler/go.mod
  httphandler/go.sum
Labels: release

#716 install.ps1 is modified to increase downloading speed as well as show progress bar
  install.ps1
Labels: feature, todo, windows, Install

#1027 setCloudMetadata only when scanning a cluster
  core/pkg/policyhandler/handlenotification.go
Labels: release/hot-fix
