Repository kubescape/kubescape, pull requests merged in 2023-08, with the labels that each got.

#1300 Scanning a single resource
  cmd/scan/scan.go
  cmd/scan/workload.go
  core/cautils/datastructures.go
  core/cautils/datastructuresmethods.go
  core/cautils/scaninfo.go
  core/cautils/workloadmappingutils.go
  core/core/initutils.go
  core/core/scan.go
  core/pkg/opaprocessor/processorhandler.go
  core/pkg/opaprocessor/processorhandler_test.go
  core/pkg/opaprocessor/processorhandlerutils.go
  core/pkg/opaprocessor/testdata/opaSessionObjMock.json
  core/pkg/opaprocessor/utils.go
  core/pkg/opaprocessor/utils_test.go
  core/pkg/policyhandler/handlepullpolicies.go
  core/pkg/resourcehandler/fieldselector.go
  core/pkg/resourcehandler/fieldselector_test.go
  core/pkg/resourcehandler/filesloader.go
  core/pkg/resourcehandler/filesloaderutils.go
  core/pkg/resourcehandler/filesloaderutils_test.go
  core/pkg/resourcehandler/handlepullresources_test.go
  core/pkg/resourcehandler/handlerpullresources.go
  core/pkg/resourcehandler/interface.go
  core/pkg/resourcehandler/k8sresources.go
  core/pkg/resourcehandler/k8sresourcesutils.go
  core/pkg/resourcehandler/k8sresourcesutils_test.go
  core/pkg/resourcehandler/queryableresource.go
  core/pkg/resourcehandler/queryableresource_test.go
  core/pkg/resourcehandler/registrydata.go
  core/pkg/resourcehandler/resourcehandlerutils.go
  core/pkg/resourcehandler/resourcehandlerutils_test.go
  core/pkg/resultshandling/reporter/v2/mockreporter_test.go
  core/pkg/resultshandling/reporter/v2/testdata/mock_opasessionobj.json
  httphandler/handlerequests/v1/datastructuremethods.go
  httphandler/handlerequests/v1/datastructuremethods_test.go
Labels: trigger-integration-test

#1324 Update GitHub Actions
  .github/workflows/00-pr-scanner.yaml
  .github/workflows/01-pr-merged.yaml
  .github/workflows/a-pr-scanner.yaml
  .github/workflows/b-binary-build-and-e2e-tests.yaml
Labels: Enhancement

#1329 Update codesee-arch-diagram.yml
  .github/workflows/codesee-arch-diagram.yml
Labels: Enhancement

#1327 Fix submit time
  core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
Labels: Bug fix

#1333 Hotfix for version 2.3.8
  .github/workflows/build-image.yaml
  core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
Labels: Bug fix

#1293 Support scanning scope
  .github/workflows/b-binary-build-and-e2e-tests.yaml
  core/cautils/datastructuresmethods.go
  core/cautils/datastructuresmethods_test.go
  core/cautils/getter/kscloudapi_test.go
  core/cautils/scaninfo.go
  core/cautils/testdata/any_file_for_test.json
  core/core/scan.go
  core/mocks/loadmocks.go
  core/pkg/opaprocessor/processorhandler.go
  core/pkg/opaprocessor/processorhandler_test.go
  core/pkg/opaprocessor/utils.go
  core/pkg/opaprocessor/utils_test.go
  core/pkg/resultshandling/printer/v2/prettyprinter.go
  go.mod
  go.sum
  httphandler/go.mod
  httphandler/go.sum
Labels: trigger-integration-test, Enhancement

#1337 scan per namespace
  cmd/scan/image.go
  cmd/scan/scan.go
  cmd/scan/workload.go
  core/core/scan.go
  core/pkg/opaprocessor/processorhandler.go
  core/pkg/opaprocessor/processorhandler_test.go
  core/pkg/opaprocessor/processorhandlerutils.go
  core/pkg/resourcehandler/k8sresources.go
  core/pkg/resourcehandler/resourcehandlerutils.go
  go.mod
  go.sum
  httphandler/go.mod
  httphandler/go.sum
  httphandler/handlerequests/v1/requestshandler.go
  httphandler/handlerequests/v1/requestshandlerutils.go
  pkg/imagescan/imagescan_test.go
Labels: Enhancement

#1338 use distroless base image
  .dockerignore
  build/Dockerfile
  core/pkg/opaprocessor/cosign_has_signature.go
  core/pkg/opaprocessor/cosign_verify.go
  go.mod
  go.sum
  httphandler/go.mod
  httphandler/go.sum
Labels: release

#1340 Update logs
  cmd/scan/image.go
  core/core/scan.go
  go.mod
  go.sum
  httphandler/go.mod
  httphandler/go.sum
Labels: Refactoring

#1304 Support unified configuration
  .github/workflows/b-binary-build-and-e2e-tests.yaml
  core/cautils/customerloader.go
  core/cautils/customerloader_test.go
  core/core/cachedconfig.go
Labels: Enhancement

#1335 Create dependabot.yaml
  .github/dependabot.yaml
Labels: documentation

#1359 Service discovery
  .github/workflows/b-binary-build-and-e2e-tests.yaml
  cmd/root.go
  cmd/rootutils.go
  cmd/scan/scan.go
  core/cautils/customerloader.go
  core/cautils/customerloader_test.go
  core/cautils/getter/interfaces.go
  core/cautils/getter/kscloudapi.go
  core/cautils/getter/kscloudapi_test.go
  core/cautils/rootinfo.go
  core/cautils/scaninfo.go
  core/cautils/scaninfo_test.go
  core/core/cachedconfig.go
  core/core/download.go
  core/core/initutils.go
  core/core/list.go
  core/core/scan.go
  core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
  core/pkg/resultshandling/reporter/v2/reporteventreceiver_test.go
  core/pkg/resultshandling/reporter/v2/reporteventreceiverutils.go
  core/pkg/resultshandling/reporter/v2/reporteventreceiverutils_test.go
  docs/providers/armo.md
  docs/providers/install.ps1
  docs/providers/install.sh
  go.mod
  go.sum
  httphandler/go.mod
  httphandler/go.sum
  httphandler/listener/init.go
Labels: Enhancement
