Repository kubescape/kubescape, pull requests merged in 2023-11, with the labels that each got.

#1481 Fix for Empty Build Number in cmd Version
  cmd/version/version.go
  cmd/version/version_test.go
Labels: Bug fix

#1490 Run binary-build job only for kubescape/kubscape
  .github/workflows/00-pr-scanner.yaml
Labels: bug bounty

#1485 Adding Test Suite for core/pkg/resultshandling/gotree
  core/pkg/resultshandling/gotree/gotree_mock.go
  core/pkg/resultshandling/gotree/gotree_test.go
Labels: Tests, bug bounty

#1483 Added Test Suite for cautils
  core/cautils/controllink_test.go
  core/cautils/display_test.go
  core/cautils/fileutils_test.go
  core/cautils/getter/getpoliciesutils_test.go
  core/cautils/getter/utils_test.go
Labels: bug bounty

#1477 Adding Test Suite for core/pkg/score
  core/pkg/score/score_test.go
Labels: Tests, bug bounty

#1487 Adding Tests and Refactoring for ruleWithKSOpaDependency Function in cautils
  core/cautils/datastructuresmethods.go
  core/cautils/versioncheck_test.go
Labels: Tests, bug bounty

#1480 Implementation of Interrupt Signal Handler
  main.go
Labels: Enhancement, bug bounty

#1494 Refactor and Improve Code for Kubescape Version Compatibility Check
  core/cautils/datastructuresmethods.go
  core/cautils/versioncheck_test.go
Labels: Refactoring, bug bounty

#1495 Adding Comprehensive Test Suite for yamlhelper Package
  core/pkg/fixhandler/yamlhelper_test.go
Labels: Tests, bug bounty

#1497 Fix for Index Out of Range Error in Malformed Policies Handling
  core/core/list.go
  core/core/list_test.go
Labels: Bug fix, bug bounty

#1500 Edge-case Handling and Test Enhancements in yamlhelper
  core/pkg/fixhandler/yamlhelper.go
  core/pkg/fixhandler/yamlhelper_test.go
Labels: Bug fix, bug bounty

#1503 Adding Test Suite for core/pkg/policyhandler
  core/pkg/policyhandler/handlepullpolicies_test.go
  core/pkg/policyhandler/handlepullpoliciesutils_test.go
Labels: Tests, bug bounty

#1501 Adding tests for core/core/initutils and fixing potential bug
  core/core/initutils.go
  core/core/initutils_test.go
Labels: Tests, bug bounty

#1505 Adding Unit Tests for cmd/shared Package
  cmd/shared/image_scan_test.go
Labels: Tests, bug bounty

#1507 Enhancement of 'update' command and addition of tests for version check
  cmd/update/update.go
  core/cautils/versioncheck.go
  core/cautils/versioncheck_test.go
Labels: Enhancement, bug bounty

#1510 Enhancement of TimedCache with Bug Fixes and Test Suite
  core/pkg/policyhandler/cache.go
  core/pkg/policyhandler/cache_test.go
Labels: Bug fix, bug bounty

#1508 Enhancement of Test Suite for cmd Packages
  cmd/completion/completion_test.go
  cmd/config/config_test.go
  cmd/config/delete_test.go
  cmd/config/set.go
  cmd/config/set_test.go
  cmd/config/view_test.go
  core/mocks/cmd_mocks.go
Labels: Tests, bug bounty

#1504 Enhancement of Test Coverage and Code Improvements in Container Scan Package
  core/pkg/containerscan/containerscan_test.go
  core/pkg/containerscan/datastructures.go
  core/pkg/containerscan/datastructuresmethods.go
  core/pkg/containerscan/elasticadapters.go
  core/pkg/containerscan/elasticdatastructures.go
  go.sum
Labels: Enhancement, bug bounty

#1502 Adding Test Suite for the core/core package
  core/core/download_test.go
  core/core/fix_test.go
  core/core/list_test.go
  core/core/scan_test.go
Labels: Tests, bug bounty

#1486 Adding Additional Test Cases for JSONDecoder in core/cautils/getter
  core/cautils/getter/getpoliciesutils.go
  core/cautils/getter/getpoliciesutils_test.go
  core/cautils/getter/json.go
  core/cautils/getter/json_test.go
  core/cautils/getter/kscloudapi.go
  core/cautils/getter/kscloudapi_test.go
  core/cautils/versioncheck.go
Labels: Tests, bug bounty

#1509 Adding Unit Tests and Bug Fix for core/cautils
  core/cautils/jsonutils_test.go
  core/cautils/krewutils_test.go
  core/cautils/kustomizedirectory.go
  core/cautils/kustomizedirectory_test.go
  core/cautils/workloadmappingutils_test.go
Labels: Tests, bug bounty

#1512 Enhancement: Added Test Suite for cmd package and Fixed Potential Crashes
  cmd/completion/completion.go
  cmd/completion/completion_test.go
  cmd/config/set_test.go
  cmd/download/download.go
  cmd/download/download_test.go
  cmd/fix/fix_test.go
  cmd/list/list.go
  cmd/list/list_test.go
  core/core/download.go
  core/core/list.go
Labels: Tests, bug bounty

#1513 Add Test Suite for cmd Packages and Fix Potential Crash in Image Subcommand
  cmd/operator/configscan_test.go
  cmd/operator/operator_test.go
  cmd/operator/scan_test.go
  cmd/operator/vulnerabilitiesscan_test.go
  cmd/patch/patch.go
  cmd/patch/patch_test.go
  cmd/scan/control_test.go
  cmd/scan/framework_test.go
  cmd/scan/image.go
  cmd/scan/image_test.go
  cmd/scan/scan_test.go
  cmd/scan/workload.go
  cmd/scan/workload_test.go
Labels: Tests, bug bounty

#1514 Enhancement: Added Unit Tests for Multiple Packages
  core/pkg/resultshandling/printer/printresults_test.go
  core/pkg/resultshandling/results_test.go
  httphandler/config/config_test.go
  httphandler/config/credentials_test.go
  internal/testutils/dir_test.go
  pkg/imagescan/imagescan_test.go
Labels: Tests, bug bounty

#1517 Enhancement of the printer package with additional tests and refactoring
  core/pkg/resultshandling/printer/v2/sarifprinter.go
  core/pkg/resultshandling/printer/v2/sarifprinter_test.go
  core/pkg/resultshandling/printer/v2/summaryhelpers_test.go
Labels: Enhancement, bug bounty

#1520 Implement Natural Sorting for Policy Listing
  core/core/list.go
  core/core/list_test.go
  go.mod
  go.sum
  httphandler/go.mod
  httphandler/go.sum
Labels: Enhancement, bug bounty

#1515 Bugfix and Tests for Image Scan Package
  pkg/imagescan/imagescan.go
  pkg/imagescan/imagescan_test.go
Labels: Bug fix, bug bounty

#1516 Bug Fix and Test Addition for sanitizeYaml and revertSanitizeYaml Functions
  core/pkg/fixhandler/fixhandler.go
  core/pkg/fixhandler/fixhandler_test.go
Labels: Bug fix, bug bounty

#1525 Enhancement and Test Suite for ResourceTable
  core/pkg/resultshandling/printer/v2/resourcetable.go
  core/pkg/resultshandling/printer/v2/resourcetable_test.go
Labels: Tests, bug bounty

#1527 Update set_test.go
  cmd/config/set_test.go
Labels: bug bounty

#1528 Enhancement and Testing of String Utilities
  core/cautils/strutils.go
  core/cautils/strutils_test.go
Labels: Enhancement, bug bounty

#1529 Update patch_test.go (Add Test Case for Non-Existent Image in GetPatchCmd)
  cmd/patch/patch_test.go
Labels: bug bounty

#1531 Update control_test.go (Add Test Case for Non-Existent Control in Get…
  cmd/scan/control_test.go
Labels: bug bounty

#1533 Update framework_test.go (Add Test Case for Non-Existent Framework in…
  cmd/scan/framework_test.go
Labels: bug bounty

#1534 Added Test Suite for Prometheus Utilities
  core/pkg/resultshandling/printer/v2/prometheusutils_test.go
Labels: Tests, bug bounty

#1538 Refactoring and Adding Tests for Resource Prioritization
  core/cautils/strutils.go
  core/cautils/strutils_test.go
  core/pkg/resourcesprioritization/prioritizationhandler.go
  core/pkg/resourcesprioritization/prioritizationhandler_test.go
Labels: Refactoring, Tests, bug bounty

#1521 Added new test cases for different shell completions in the completion package to enhance test coverage.
  cmd/completion/completion_test.go
Labels: bug bounty

#1540 Enhancement of YAML File Validation and Corresponding Test Cases
  core/pkg/hostsensorutils/hostsensordeploy.go
  core/pkg/hostsensorutils/hostsensordeploy_test.go
  core/pkg/hostsensorutils/testdata/empty_hostsensor.yaml
  core/pkg/hostsensorutils/testdata/hostsensor.yaml
  core/pkg/hostsensorutils/testdata/notAYamlFile.txt
Labels: Enhancement, Tests, bug bounty

#1536 Enhancement and Test Suite for Printer Functions
  core/pkg/resultshandling/printer/v2/jsonprinter.go
  core/pkg/resultshandling/printer/v2/jsonprinter_test.go
  core/pkg/resultshandling/printer/v2/junit.go
  core/pkg/resultshandling/printer/v2/junit_test.go
  core/pkg/resultshandling/printer/v2/pdf.go
  core/pkg/resultshandling/printer/v2/pdf_test.go
  core/pkg/resultshandling/printer/v2/prometheus.go
  core/pkg/resultshandling/printer/v2/prometheus_test.go
Labels: Enhancement, bug bounty

#1545 Enhancements and Tests for Configuration Printer
  core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/categorytable_test.go
  core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/frameworkscan.go
  core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/frameworkscan_test.go
Labels: Refactoring, Tests, bug bounty

#1542 Added new tests in the imagewriter package
  core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/imageprinter/tablewriter_test.go
  core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/imageprinter/utils_test.go
Labels: Tests, bug bounty, bug_fix

#1539 Performance Enhancements and Test Additions in prettyprinter/utils.go
  core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/utils/utils_test.go
  core/pkg/resultshandling/printer/v2/prettyprinter/utils.go
  core/pkg/resultshandling/printer/v2/prettyprinter/utils_test.go
Labels: Enhancement, Tests, bug bounty

#1537 Addition of Tests for the PrettyPrinter Package
  core/pkg/resultshandling/printer/v2/prettyprinter/clusterscan_test.go
  core/pkg/resultshandling/printer/v2/prettyprinter/frameworkscan_test.go
  core/pkg/resultshandling/printer/v2/prettyprinter/imagescan_test.go
Labels: Tests, bug bounty

#1549 Addition of new tests for junit printer, version check and PDF printer
  core/cautils/versioncheck_test.go
  core/pkg/resultshandling/printer/v2/junit_test.go
  core/pkg/resultshandling/printer/v2/pdf_test.go
Labels: Tests, bug bounty

#1544 Enhancement of Logging Mechanisms for KS Cloud Usage
  core/core/initutils.go
Labels: Enhancement, bug bounty
